---
#
# Ansible managed
#
repository:
  description: Install the Enpass password manager on your system.
  homepage: https://buluma.github.io/
  topics: enpass, passwordmanager, password, security, ansible, molecule, tox, playbook
